library(plyr)
rides <- read.csv(file="/Users/maxlakin/data/nyc-taxi-data/data/yellow_tripdata_2015-12.csv",head=TRUE,sep=",")
names(rides)
class(head(rides$tpep_pickup_datetime,1))
day<-format(as.Date(rides$tpep_pickup_datetime,format="%Y-%m-%d %H:%M:%S"), "%d")
head(day,2)
c <- count(day)
head(c,3)
plot(c$freq/1000, type="l",xlab="day",ylab="pickups (K)")
